on: [push]

jobs:
  split_evaluator_local:
    runs-on: ubuntu-latest
    name: A job to test the Split evaluator github action
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: WORKSPACE
        run: echo "workspace ${{ env.GITHUB_WORKSPACE }}"

      - name: Evaluate action step
        id: evaluator
        uses: splitio/split-evaluator-action@v1.0-rc1
        with:
          api-key: 'localhost'
          key: ${{ secrets.SPLIT_EVAL_KEY }}
          splits: |
            enable_paywall
            api_verbose

      # Use the output from the `evaluator` step
      - name: Get the output evaluation
        run: echo "The result was ${{ steps.evaluator.outputs.result }}"